// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/reservation/v1/reservation.proto

package reservationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleType int32

const (
	VehicleType_VEHICLE_TYPE_UNSPECIFIED VehicleType = 0
	VehicleType_CAR                      VehicleType = 1
	VehicleType_MOTORCYCLE               VehicleType = 2
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "VEHICLE_TYPE_UNSPECIFIED",
		1: "CAR",
		2: "MOTORCYCLE",
	}
	VehicleType_value = map[string]int32{
		"VEHICLE_TYPE_UNSPECIFIED": 0,
		"CAR":                      1,
		"MOTORCYCLE":               2,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_reservation_v1_reservation_proto_enumTypes[0].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_api_proto_reservation_v1_reservation_proto_enumTypes[0]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

type ReservationState int32

const (
	ReservationState_RESERVATION_STATE_UNSPECIFIED ReservationState = 0
	ReservationState_PENDING                       ReservationState = 1
	ReservationState_CONFIRMED                     ReservationState = 2
	ReservationState_ACTIVE                        ReservationState = 3
	ReservationState_COMPLETED                     ReservationState = 4
	ReservationState_CANCELLED                     ReservationState = 5
	ReservationState_EXPIRED                       ReservationState = 6
)

// Enum value maps for ReservationState.
var (
	ReservationState_name = map[int32]string{
		0: "RESERVATION_STATE_UNSPECIFIED",
		1: "PENDING",
		2: "CONFIRMED",
		3: "ACTIVE",
		4: "COMPLETED",
		5: "CANCELLED",
		6: "EXPIRED",
	}
	ReservationState_value = map[string]int32{
		"RESERVATION_STATE_UNSPECIFIED": 0,
		"PENDING":                       1,
		"CONFIRMED":                     2,
		"ACTIVE":                        3,
		"COMPLETED":                     4,
		"CANCELLED":                     5,
		"EXPIRED":                       6,
	}
)

func (x ReservationState) Enum() *ReservationState {
	p := new(ReservationState)
	*p = x
	return p
}

func (x ReservationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_reservation_v1_reservation_proto_enumTypes[1].Descriptor()
}

func (ReservationState) Type() protoreflect.EnumType {
	return &file_api_proto_reservation_v1_reservation_proto_enumTypes[1]
}

func (x ReservationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationState.Descriptor instead.
func (ReservationState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	SpotId        string                 `protobuf:"bytes,3,opt,name=spot_id,json=spotId,proto3" json:"spot_id,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,4,opt,name=vehicle_type,json=vehicleType,proto3,enum=parkirpintar.reservation.v1.VehicleType" json:"vehicle_type,omitempty"`
	State         ReservationState       `protobuf:"varint,5,opt,name=state,proto3,enum=parkirpintar.reservation.v1.ReservationState" json:"state,omitempty"`
	HoldStart     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=hold_start,json=holdStart,proto3" json:"hold_start,omitempty"`
	HoldEnd       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=hold_end,json=holdEnd,proto3" json:"hold_end,omitempty"`
	ConfirmedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	CheckedInAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	CheckedOutAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=checked_out_at,json=checkedOutAt,proto3" json:"checked_out_at,omitempty"`
	Version       int32                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Reservation) GetSpotId() string {
	if x != nil {
		return x.SpotId
	}
	return ""
}

func (x *Reservation) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *Reservation) GetState() ReservationState {
	if x != nil {
		return x.State
	}
	return ReservationState_RESERVATION_STATE_UNSPECIFIED
}

func (x *Reservation) GetHoldStart() *timestamppb.Timestamp {
	if x != nil {
		return x.HoldStart
	}
	return nil
}

func (x *Reservation) GetHoldEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.HoldEnd
	}
	return nil
}

func (x *Reservation) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *Reservation) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *Reservation) GetCheckedOutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedOutAt
	}
	return nil
}

func (x *Reservation) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Reservation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateReservationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DriverId        string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleType     VehicleType            `protobuf:"varint,2,opt,name=vehicle_type,json=vehicleType,proto3,enum=parkirpintar.reservation.v1.VehicleType" json:"vehicle_type,omitempty"`
	Mode            string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`                                                // SYSTEM_ASSIGNED | USER_SELECTED
	PreferredSpotId string                 `protobuf:"bytes,4,opt,name=preferred_spot_id,json=preferredSpotId,proto3" json:"preferred_spot_id,omitempty"` // required iff mode = USER_SELECTED
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReservationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateReservationRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *CreateReservationRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateReservationRequest) GetPreferredSpotId() string {
	if x != nil {
		return x.PreferredSpotId
	}
	return ""
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *CancelReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *CheckInRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckInRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CheckInRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CheckOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *CheckOutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *GetReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   VehicleType            `protobuf:"varint,1,opt,name=vehicle_type,json=vehicleType,proto3,enum=parkirpintar.reservation.v1.VehicleType" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *GetAvailabilityRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

type FloorAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Floor         int32                  `protobuf:"varint,1,opt,name=floor,proto3" json:"floor,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorAvailability) Reset() {
	*x = FloorAvailability{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorAvailability) ProtoMessage() {}

func (x *FloorAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorAvailability.ProtoReflect.Descriptor instead.
func (*FloorAvailability) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *FloorAvailability) GetFloor() int32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *FloorAvailability) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableCount int32                  `protobuf:"varint,1,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	ByFloor        []*FloorAvailability   `protobuf:"bytes,2,rep,name=by_floor,json=byFloor,proto3" json:"by_floor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAvailabilityResponse) Reset() {
	*x = GetAvailabilityResponse{}
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityResponse) ProtoMessage() {}

func (x *GetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_reservation_v1_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_reservation_v1_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailabilityResponse) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *GetAvailabilityResponse) GetByFloor() []*FloorAvailability {
	if x != nil {
		return x.ByFloor
	}
	return nil
}

var File_api_proto_reservation_v1_reservation_proto protoreflect.FileDescriptor

const file_api_proto_reservation_v1_reservation_proto_rawDesc = "" +
	"\n" +
	"*api/proto/reservation/v1/reservation.proto\x12\x1bparkirpintar.reservation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x04\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x17\n" +
	"\aspot_id\x18\x03 \x01(\tR\x06spotId\x12K\n" +
	"\fvehicle_type\x18\x04 \x01(\x0e2(.parkirpintar.reservation.v1.VehicleTypeR\vvehicleType\x12C\n" +
	"\x05state\x18\x05 \x01(\x0e2-.parkirpintar.reservation.v1.ReservationStateR\x05state\x129\n" +
	"\n" +
	"hold_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tholdStart\x125\n" +
	"\bhold_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aholdEnd\x12=\n" +
	"\fconfirmed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x12>\n" +
	"\rchecked_in_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcheckedInAt\x12@\n" +
	"\x0echecked_out_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fcheckedOutAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc4\x01\n" +
	"\x18CreateReservationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12K\n" +
	"\fvehicle_type\x18\x02 \x01(\x0e2(.parkirpintar.reservation.v1.VehicleTypeR\vvehicleType\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12*\n" +
	"\x11preferred_spot_id\x18\x04 \x01(\tR\x0fpreferredSpotId\"+\n" +
	"\x19ConfirmReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x18CancelReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Z\n" +
	"\x0eCheckInRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"!\n" +
	"\x0fCheckOutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15GetReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x16GetAvailabilityRequest\x12K\n" +
	"\fvehicle_type\x18\x01 \x01(\x0e2(.parkirpintar.reservation.v1.VehicleTypeR\vvehicleType\"?\n" +
	"\x11FloorAvailability\x12\x14\n" +
	"\x05floor\x18\x01 \x01(\x05R\x05floor\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8d\x01\n" +
	"\x17GetAvailabilityResponse\x12'\n" +
	"\x0favailable_count\x18\x01 \x01(\x05R\x0eavailableCount\x12I\n" +
	"\bby_floor\x18\x02 \x03(\v2..parkirpintar.reservation.v1.FloorAvailabilityR\abyFloor*D\n" +
	"\vVehicleType\x12\x1c\n" +
	"\x18VEHICLE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03CAR\x10\x01\x12\x0e\n" +
	"\n" +
	"MOTORCYCLE\x10\x02*\x88\x01\n" +
	"\x10ReservationState\x12!\n" +
	"\x1dRESERVATION_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tCONFIRMED\x10\x02\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\v\n" +
	"\aEXPIRED\x10\x062\xac\x06\n" +
	"\x12ReservationService\x12t\n" +
	"\x11CreateReservation\x125.parkirpintar.reservation.v1.CreateReservationRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12v\n" +
	"\x12ConfirmReservation\x126.parkirpintar.reservation.v1.ConfirmReservationRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12t\n" +
	"\x11CancelReservation\x125.parkirpintar.reservation.v1.CancelReservationRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12`\n" +
	"\aCheckIn\x12+.parkirpintar.reservation.v1.CheckInRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12b\n" +
	"\bCheckOut\x12,.parkirpintar.reservation.v1.CheckOutRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12n\n" +
	"\x0eGetReservation\x122.parkirpintar.reservation.v1.GetReservationRequest\x1a(.parkirpintar.reservation.v1.Reservation\x12|\n" +
	"\x0fGetAvailability\x123.parkirpintar.reservation.v1.GetAvailabilityRequest\x1a4.parkirpintar.reservation.v1.GetAvailabilityResponseBMZKgithub.com/farid/reservation-service/api/proto/reservation/v1;reservationv1b\x06proto3"

var (
	file_api_proto_reservation_v1_reservation_proto_rawDescOnce sync.Once
	file_api_proto_reservation_v1_reservation_proto_rawDescData []byte
)

func file_api_proto_reservation_v1_reservation_proto_rawDescGZIP() []byte {
	file_api_proto_reservation_v1_reservation_proto_rawDescOnce.Do(func() {
		file_api_proto_reservation_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_reservation_v1_reservation_proto_rawDesc), len(file_api_proto_reservation_v1_reservation_proto_rawDesc)))
	})
	return file_api_proto_reservation_v1_reservation_proto_rawDescData
}

var file_api_proto_reservation_v1_reservation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_reservation_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_reservation_v1_reservation_proto_goTypes = []any{
	(VehicleType)(0),                  // 0: parkirpintar.reservation.v1.VehicleType
	(ReservationState)(0),             // 1: parkirpintar.reservation.v1.ReservationState
	(*Reservation)(nil),               // 2: parkirpintar.reservation.v1.Reservation
	(*CreateReservationRequest)(nil),  // 3: parkirpintar.reservation.v1.CreateReservationRequest
	(*ConfirmReservationRequest)(nil), // 4: parkirpintar.reservation.v1.ConfirmReservationRequest
	(*CancelReservationRequest)(nil),  // 5: parkirpintar.reservation.v1.CancelReservationRequest
	(*CheckInRequest)(nil),            // 6: parkirpintar.reservation.v1.CheckInRequest
	(*CheckOutRequest)(nil),           // 7: parkirpintar.reservation.v1.CheckOutRequest
	(*GetReservationRequest)(nil),     // 8: parkirpintar.reservation.v1.GetReservationRequest
	(*GetAvailabilityRequest)(nil),    // 9: parkirpintar.reservation.v1.GetAvailabilityRequest
	(*FloorAvailability)(nil),         // 10: parkirpintar.reservation.v1.FloorAvailability
	(*GetAvailabilityResponse)(nil),   // 11: parkirpintar.reservation.v1.GetAvailabilityResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_api_proto_reservation_v1_reservation_proto_depIdxs = []int32{
	0,  // 0: parkirpintar.reservation.v1.Reservation.vehicle_type:type_name -> parkirpintar.reservation.v1.VehicleType
	1,  // 1: parkirpintar.reservation.v1.Reservation.state:type_name -> parkirpintar.reservation.v1.ReservationState
	12, // 2: parkirpintar.reservation.v1.Reservation.hold_start:type_name -> google.protobuf.Timestamp
	12, // 3: parkirpintar.reservation.v1.Reservation.hold_end:type_name -> google.protobuf.Timestamp
	12, // 4: parkirpintar.reservation.v1.Reservation.confirmed_at:type_name -> google.protobuf.Timestamp
	12, // 5: parkirpintar.reservation.v1.Reservation.checked_in_at:type_name -> google.protobuf.Timestamp
	12, // 6: parkirpintar.reservation.v1.Reservation.checked_out_at:type_name -> google.protobuf.Timestamp
	12, // 7: parkirpintar.reservation.v1.Reservation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: parkirpintar.reservation.v1.CreateReservationRequest.vehicle_type:type_name -> parkirpintar.reservation.v1.VehicleType
	0,  // 9: parkirpintar.reservation.v1.GetAvailabilityRequest.vehicle_type:type_name -> parkirpintar.reservation.v1.VehicleType
	10, // 10: parkirpintar.reservation.v1.GetAvailabilityResponse.by_floor:type_name -> parkirpintar.reservation.v1.FloorAvailability
	3,  // 11: parkirpintar.reservation.v1.ReservationService.CreateReservation:input_type -> parkirpintar.reservation.v1.CreateReservationRequest
	4,  // 12: parkirpintar.reservation.v1.ReservationService.ConfirmReservation:input_type -> parkirpintar.reservation.v1.ConfirmReservationRequest
	5,  // 13: parkirpintar.reservation.v1.ReservationService.CancelReservation:input_type -> parkirpintar.reservation.v1.CancelReservationRequest
	6,  // 14: parkirpintar.reservation.v1.ReservationService.CheckIn:input_type -> parkirpintar.reservation.v1.CheckInRequest
	7,  // 15: parkirpintar.reservation.v1.ReservationService.CheckOut:input_type -> parkirpintar.reservation.v1.CheckOutRequest
	8,  // 16: parkirpintar.reservation.v1.ReservationService.GetReservation:input_type -> parkirpintar.reservation.v1.GetReservationRequest
	9,  // 17: parkirpintar.reservation.v1.ReservationService.GetAvailability:input_type -> parkirpintar.reservation.v1.GetAvailabilityRequest
	2,  // 18: parkirpintar.reservation.v1.ReservationService.CreateReservation:output_type -> parkirpintar.reservation.v1.Reservation
	2,  // 19: parkirpintar.reservation.v1.ReservationService.ConfirmReservation:output_type -> parkirpintar.reservation.v1.Reservation
	2,  // 20: parkirpintar.reservation.v1.ReservationService.CancelReservation:output_type -> parkirpintar.reservation.v1.Reservation
	2,  // 21: parkirpintar.reservation.v1.ReservationService.CheckIn:output_type -> parkirpintar.reservation.v1.Reservation
	2,  // 22: parkirpintar.reservation.v1.ReservationService.CheckOut:output_type -> parkirpintar.reservation.v1.Reservation
	2,  // 23: parkirpintar.reservation.v1.ReservationService.GetReservation:output_type -> parkirpintar.reservation.v1.Reservation
	11, // 24: parkirpintar.reservation.v1.ReservationService.GetAvailability:output_type -> parkirpintar.reservation.v1.GetAvailabilityResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_reservation_v1_reservation_proto_init() }
func file_api_proto_reservation_v1_reservation_proto_init() {
	if File_api_proto_reservation_v1_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_reservation_v1_reservation_proto_rawDesc), len(file_api_proto_reservation_v1_reservation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_reservation_v1_reservation_proto_goTypes,
		DependencyIndexes: file_api_proto_reservation_v1_reservation_proto_depIdxs,
		EnumInfos:         file_api_proto_reservation_v1_reservation_proto_enumTypes,
		MessageInfos:      file_api_proto_reservation_v1_reservation_proto_msgTypes,
	}.Build()
	File_api_proto_reservation_v1_reservation_proto = out.File
	file_api_proto_reservation_v1_reservation_proto_goTypes = nil
	file_api_proto_reservation_v1_reservation_proto_depIdxs = nil
}
